---
title: "IS606-Ch1-Hw"
author: "Daniel Dittenhafer"
date: "September 1, 2015"
output: html_document
---

### 1.8 Smoking habits of UK residents

#### (a) What does each row of the data matrix represent?

Each row of the data matrix represents a sample.

#### (b) How many participants were included in the survey?

Assuming row 1961 is the last row of the data, then 1691 participants were included in the survey.

#### (c) Indicate whether each variable in the study is numerical or categorical.

* sex: Categorical
* age: Numerical, Discrete
* marital: Categorical
* grossIncome: Categorical, Ordinal
* smoke: Categorical
* amtWeekends: Numerical, Discrete
* amtWeekdays: Numerical, Discrete


### 1.10 Cheaters, scope of inference

#### (a) Identify the population of interest and the sample in this study.

The population is children between ages 5 and 15. The sample was 160 children within the age range.

#### (b) Comment on whether or not the results of the study can be generalized to the population, and whether the findings of the study can be used to establish a causal relationship.

The sample size is small compared to the assumed population (all children 5-15). Also, it isn't clear how the sample was selected. As such, I am skeptical that the results could or should be generalted to the population.

The study is described as an experiment, with the independent variable being the instruction to cheat (or lack of instruction), and dependent variable being the cheating outcome. Based on the information in the 1.5 exercise write-up, a causal relationship is not supported. Age appears to be a confounding variable, but age alone is unlikely to be the driver... rather the maturity of the child more likely drives the probability of cheating. Either way, I don't see how this study could be used to establish a causal relationship.


### 1.28 Reading the paper

#### (a) Risks: Smokers Found More Prone to Dementia

Based on the study, I take away the conclusion that smoking (implied to be tobacco) is correlated with dementia. This may be related to a chemical response from nicotine, but may not be. It could be driven instead by another chemical in the smoke. The description of the study suggests an "experiement" structure, an individual would always be aware if they are smoking or not, therefore a blind control group would not be possible.

#### (b) The School Bully Is Sleepy

The statement "The study shows that sleep disorders lead to bullying in school children" is not justified. The conclusion I draw is that there is a correlation between sleep disorders and behavioral issues. There may be another factor which is driving both the sleep disorder and the behavioral issue. 

### 1.36 Exercise and mental health

#### (a) What type of study is this?

This is a randomized experiment.

#### (b) What are the treatment and control groups in this study?

The treatment group is the the group instructed to exercise twice a week. The control group is the group instructed not to exercise.

#### (c) Does this study make use of blocking? If so, what is the blocking variable?

Yes, this study makes use of blocking in respect to the age of the participants. (p24) 

#### (d) Does this study make use of blinding?

No, this study does not make use of blinding. The participants know if they are exercising or not.

#### (e) Comment on whether or not the results of the study can be used to establish a causal relationship between exercise and mental health?

Given the exeriment design, a causal relationship conclusion is possible. The study proposal does not indicate how big the sample size will be, therefore I am unable to conclude that the study could be generalized to the population at large. 

#### (f) Suppose you are given the task of determining if this proposed study should get funding. Would you have any reservations about the study proposal?


```{r}

```

